version: '3'
services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 8080:6379

  web:
    container_name: web
    image: jungminleeee/monggeul-web
    expose:
      - 8080
    ports:
      - 8080:8080



  nginx:
    container_name: nginx
    image: jungminleeee/monggeul-nginx
    ports:
      - 80:80
    depends_on:
      - web




