version: '3'
services:

  web:
    container_name: web
    image: jungminleeee/monggeul-web
    expose:
      - 8080
    ports:
      - 8080:8080
    logging:
      driver: awslogs
      options:
        awslogs-group: "monggeul-log"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "monggeul-backend-log"

  nginx:
    container_name: nginx
    image: jungminleeee/monggeul-nginx
    ports:
      - 80:80
    depends_on:
      - web

