spring:

  main:
    allow-circular-references: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

#  config:
#    import:
#      - application-aws.yml


  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql

  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: 127.0.0.1
    port: 6379
    timeout: 3000 #ms connection timeout

  security:
    oauth2:
      client:
        registration:
          google:

            client-id: 1078527416021-a3p9mn4i1a0vid1uog9lh4eg51ad1m0h.apps.googleusercontent.com
            client-secret: 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




