spring:

  main:
    allow-circular-references: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secrets.RDS_HOSTNAME}:3306/${secrets.RDS_DBNAME}
    username: ${secrets.RDS_USERNAME}
    password: ${secrets.RDS_PASSWORD}


  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql



