spring:

  main:
    allow-circular-references: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  config:
    import:
      - application-aws.yml


  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql


  security:
    oauth2:
      client:
        registration:
          google:

            client-id: 1078527416021-a3p9mn4i1a0vid1uog9lh4eg51ad1m0h.apps.googleusercontent.com
            client-secret: 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




