spring:

  main:
    allow-circular-references: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  config:
    import:
      - application-aws.yml


  jpa:

    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000 #ms connection timeout



